package com.github.drbookings;

import javax.money.MonetaryAmount;

/**
 * Supplies a {@link MonetaryAmount} that is generated by one or more
 * {@link Booking booking}.
 *
 * @author Alexander Kerner
 * @date 2018-11-14
 *
 */
public interface MonetaryAmountFromBookingsSupplier2 extends MonetaryAmountSupplier<Booking> {
}
